<?php

/**
 * @file
 * Contains custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the custom module.
        case 'help.page.custom':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('My Awesome Module') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function custom_theme($existing, $type, $theme, $path)
{
    return [
        'custom_theme_hook' => [
            'render element' => 'children',
            'template' => 'custom_theme_hook',
            'path' => $path . '/templates',
            'variables' => [
                'header' => 'Yet another default text.',
                'rows' => 'Yet another default text.',
                'caption' => 'Heading',
            ],
        ],
    ];
}
